tensorflow:
  modelFetch: Openpose/concat_stage7
  #model: https://storage.googleapis.com/scdf-tensorflow-models/pose-estimation/2018-05-14-cmu-graph_opt.pb
  model: https://storage.googleapis.com/scdf-tensorflow-models/pose-estimation/2018-30-05-mobilenet_thin_graph_opt.pb
  pose:
    estimation:
      minBodyPartCount: 5
