tensorflow:
  modelFetch: detection_scores,detection_classes,detection_boxes,num_detections
  model: https://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz#frozen_inference_graph.pb
  object:
    detection:
      labels: https://storage.googleapis.com/scdf-tensorflow-models/object-detection/mscoco_label_map.pbtxt
